### ISSUE TITLE
2016 Summer TODO List

### ISSUE THREAD

**Issue by JimmyYW** [JimmyYW/IC-Schedule-2016#4]
Here is a summer TODO list (not in order yet):
- [ ] Improve scheduling.py
- [ ] Add the event page!
- [ ] Show schedule in a better way!! (Of course we need to...)
- [ ] Add the pre-reg stage (maybe)
- [ ] Improve scrapper make it automatic and get description/name (Wow so much work)
- [ ] View: Add delete from cart function 
- [ ] View: Clean up
- [ ] Models: Update to new models (loaction, cap, room...)
- [ ] Models: Add the user function!!
- [ ] Outlink bootstrap, JQuery
- [ ] Finish Design 
- [ ] Clean up file structure
- [ ] Clean up js function
- [ ] Resolve AWS hosting issue !! mod_wsgi !! (Maybe also have something to do with the way run.py set      up. Or may apache just not play well with python 3+) 
- [ ] Clean up jinja2 templates
- [ ] Correct static link syntax
- [ ] Landing page and other content (how it works, links, report issue, Q&A about data, contribute and
    donates etc  ad/links to textbook Maybe???)
- [ ] Mobile friendly 
- [ ] Add commons
